[build]
  command = "echo Building"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "sequelize"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true